"""split spreadsheet add schedule steps reply detection

Revision ID: 22b8bcf2936d
Revises: b26bc8c1f04f
Create Date: 2026-02-15 17:05:11.911542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22b8bcf2936d'
down_revision: Union[str, Sequence[str], None] = 'b26bc8c1f04f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reply_check_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('history_id', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaign_schedule_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('send_date', sa.Date(), nullable=True),
    sa.Column('relative_days', sa.Integer(), nullable=True),
    sa.Column('send_time', sa.Time(), nullable=False),
    sa.Column('email_template_ref', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('campaigns', sa.Column('recipients_filename', sa.String(length=255), nullable=True))
    op.add_column('campaigns', sa.Column('schedule_filename', sa.String(length=255), nullable=True))
    op.drop_column('campaigns', 'spreadsheet_filename')
    op.add_column('emails', sa.Column('thread_id', sa.String(length=255), nullable=True))
    op.add_column('emails', sa.Column('step_order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emails', 'step_order')
    op.drop_column('emails', 'thread_id')
    op.add_column('campaigns', sa.Column('spreadsheet_filename', sa.VARCHAR(length=255), nullable=True))
    op.drop_column('campaigns', 'schedule_filename')
    op.drop_column('campaigns', 'recipients_filename')
    op.drop_table('campaign_schedule_steps')
    op.drop_table('reply_check_state')
    # ### end Alembic commands ###
